### ISSUE TITLE
Crowdin translation issues

### ISSUE THREAD

**Issue by rockgem** [Crazy-Marvin/PimplePopper#103]
Looking for someone who have experience in using **Crowdin** as translations management. **To look into a bug which causes Crowdin to automatically add an empty language key (" ") into the translation.csv file**. 
It is such a mystery to me as it should only be adding language keys like en, fr, zh_CN into the the csv file **but here, it also adds an extra column with an empty key** and it causes godot to not automatically re-import and read the translation.csv file when pulling the commits from crowdin.

As of now, the workaround I do is to manually delete the extra column by editing the translation.csv file itself.
Read how to edit the file here: https://docs.godotengine.org/en/stable/tutorials/assets_pipeline/importing_translations.html#doc-importing-translations

**Comment by CrazyMarvin** [comment]
@Andrulko helped me with the initial setup. Do you know what could cause the empty string? 🤔

**Comment by rockgem** [comment]
> 

i really do not know. lol

**Comment by rockgem** [comment]
> @Andrulko helped me with the initial setup. Do you know what could cause the empty string? 🤔

i really do not know. lol

**Comment by CrazyMarvin** [comment]
I fixed the [translation.csv](https://github.com/Crazy-Marvin/PimplePopper/files/11174610/translation.csv) file with commit 16a10d30a97cb711b5423b04966a92b74065e95e hopefully.

**Comment by CrazyMarvin** [comment]
Let's keep an eye on it. I will close this issue for now.
